name: sync git-repo auto
on:
  schedule:
    - cron: '0 18 * * *'  # 每天 UTC 18:00 = 北京时间 2:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        run: |
          git clone https://github.com/GerritCodeReview/git-repo
          cd git-repo
          git fetch --all
          git remote add gitee https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/sobergou/git-repo.git
        
      - name: push gitee
        run: |
          cd git-repo
          git push --force --all gitee
          git push --force --tags gitee
